### ISSUE TITLE
Set length of curried functions correctly.

### ISSUE THREAD

**Issue by NodeGuy** [NodeGuy/generic#2]
Options:
- Choose a library other than [fj-curry](https://github.com/fp-js/fj-curry) that does it properly.
- Submit a pull request to fj-curry to fix it.
- Create our own curry library.

**Comment by natemc** [comment]
OK, I get what you're looking for now.  A separate library with public functions for curry and curryN.  How about a public function for setLength/arity (useful for parameter binding)?

**Comment by NodeGuy** [comment]
I've swapped out fj-curry with variadic currying integrated into the dispatch function in the `beta` branch.  The interface is now `{curry: true}` instead of `{curry: 2}`.  Do you have a use case for setting the generic function length?  I would argue it's now unknowable automatically given that different methods of the same function may have different arities.

**Comment by NodeGuy** [comment]
Please let me know if this is important to you and we can re-open.
